version: '3'
services:
    personal-api-development:
        image: personal-api-development
        container_name: personal-api-development
        restart: always
        build:
            context: .
        ports:
            - 9036:3030
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
